// GENERATED CODE - MANUALLY CREATED
// DO NOT EDIT THIS FILE DIRECTLY
part of 'expense.dart';

class CategoryAdapter extends TypeAdapter<Category> {
  @override
  final int typeId = 0;

  @override
  Category read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return Category.food;
      case 1:
        return Category.travel;
      case 2:
        return Category.work;
      case 3:
        return Category.leisure;
      default:
        return Category.food;
    }
  }

  @override
  void write(BinaryWriter writer, Category obj) {
    switch (obj) {
      case Category.food:
        writer.writeByte(0);
        break;
      case Category.travel:
        writer.writeByte(1);
        break;
      case Category.work:
        writer.writeByte(2);
        break;
      case Category.leisure:
        writer.writeByte(3);
        break;
    }
  }
}

class ExpenseAdapter extends TypeAdapter<Expense> {
  @override
  final int typeId = 1;

  @override
  Expense read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Expense(
      title: fields[1] as String,
      amount: fields[2] as double,
      dateTime: fields[3] as DateTime,
      category: fields[4] as Category,
    )..id = fields[0] as String;
  }

  @override
  void write(BinaryWriter writer, Expense obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.amount)
      ..writeByte(3)
      ..write(obj.dateTime)
      ..writeByte(4)
      ..write(obj.category);
  }
}
